name: 🎮 Деплой документации игры

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  build-docs:
    name: 🔨 Сборка документации
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout кода
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: 🐍 Настройка Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: 📦 Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 🔨 Сборка документации
      run: |
        mkdocs build --verbose --strict
        echo "✅ Документация собрана"
    
    - name: 💾 Сохранение артефактов
      uses: actions/upload-artifact@v4
      with:
        name: game-documentation
        path: site/
        retention-days: 30

  deploy:
    name: 🚀 Деплой на GitHub Pages  
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: 📥 Скачивание документации
      uses: actions/download-artifact@v4
      with:
        name: game-documentation
        path: site/
    
    - name: 🌐 Настройка GitHub Pages
      uses: actions/configure-pages@v4
    
    - name: 📤 Загрузка в GitHub Pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: site/
    
    - name: 🚀 Деплой в GitHub Pages
      uses: actions/deploy-pages@v2
